const { cmd } = require("../command");
const axios = require("axios");
const yts = require("yt-search");
const config = require("../config");

cmd({
    pattern: "song",
    alias: ["yta", "mp3", "play"],
    react: "🎧",
    desc: "Download YouTube MP3 with selection menu",
    category: "download",
    filename: __filename,
}, async (bot, mek, m, { from, q, reply, prefix }) => {
    try {
        if (!q) return reply("🎧 *ZANTA-MD SONG SEARCH*\n\nExample: .song alone");

        const search = await yts(q);
        const video = search.videos[0];
        if (!video) return reply("❌ No results found on YouTube.");

        let msg = `🎵 *ZANTA AUDIO PLAYER* 🎵\n\n` +
                  `📝 *Title:* ${video.title}\n` +
                  `👤 *Artist:* ${video.author.name}\n` +
                  `⏱️ *Duration:* ${video.timestamp}\n` +
                  `🔗 *Link:* ${video.url}\n\n` +
                  `*Reply with a number:* \n\n` +
                  `1️⃣ *Audio File* (MPEG)\n` +
                  `2️⃣ *Document File* (MP3)\n\n` +
                  `> *© ZANTA-MD SONG SERVICE*`;

        const sentMsg = await bot.sendMessage(from, { 
            image: { url: video.thumbnail }, 
            caption: msg 
        }, { quoted: mek });

        // --- Reply Listener එක මෙතනින් පටන් ගනී ---
        const listener = async (update) => {
            const msgUpdate = update.messages[0];
            if (!msgUpdate.message) return;

            const body = msgUpdate.message.conversation || 
                         msgUpdate.message.extendedTextMessage?.text || 
                         msgUpdate.message.buttonsResponseMessage?.selectedButtonId;

            // පරීක්ෂා කිරීම: රිප්ලයි එක කළේ කලින් යැවූ මැසේජ් එකටද සහ අංකය 1 හෝ 2 ද කියා
            const isReplyToBot = msgUpdate.message.extendedTextMessage?.contextInfo?.stanzaId === sentMsg.key.id;

            if (isReplyToBot && (body === '1' || body === '2')) {
                await bot.sendMessage(from, { react: { text: '⏳', key: msgUpdate.key } });

                try {
                    const finalLink = await getDownloadLink(video.url);
                    if (!finalLink) return reply("❌ Download link not found.");

                    if (body === '1') {
                        // Audio එවන්න
                        await bot.sendMessage(from, { 
                            audio: { url: finalLink }, 
                            mimetype: "audio/mpeg", 
                            ptt: false 
                        }, { quoted: msgUpdate });
                    } else if (body === '2') {
                        // Document එවන්න
                        await bot.sendMessage(from, { 
                            document: { url: finalLink }, 
                            mimetype: "audio/mpeg", 
                            fileName: `${video.title}.mp3`,
                            caption: "> *© Generated by ZANTA-MD*"
                        }, { quoted: msgUpdate });
                    }

                    await bot.sendMessage(from, { react: { text: '✅', key: msgUpdate.key } });
                } catch (err) {
                    console.error(err);
                    reply("❌ Error downloading audio.");
                }

                // වැඩේ ඉවර වුණාම Listener එක ඉවත් කරන්න
                bot.ev.off('messages.upsert', listener);
            }
        };

        // Listener එක Register කිරීම
        bot.ev.on('messages.upsert', listener);

        // විනාඩි 5කට පසු රිප්ලයි එකක් නැත්නම් ඉබේම Listener එක නතර කරන්න
        setTimeout(() => {
            bot.ev.off('messages.upsert', listener);
        }, 300000);

    } catch (e) {
        console.log("SONG ERROR:", e);
        reply("❌ *Error:* " + e.message);
    }
});

// --- API Logic එක පොදු Function එකක් ලෙස ---
async function getDownloadLink(videoUrl) {
    try {
        // Manul API
        const apiUrl = `https://api-site-x-by-manul.vercel.app/convert?mp3=${encodeURIComponent(videoUrl)}&apikey=Manul-Official`;
        const response = await axios.get(apiUrl);
        if (response.data?.status && response.data.data?.url) return response.data.data.url;

        // Backup API
        const backupUrl = `https://api.giftedtech.my.id/api/download/dlmp3?url=${encodeURIComponent(videoUrl)}&apikey=gifted`;
        const backup = await axios.get(backupUrl);
        return backup.data.result?.download_url;
    } catch (e) {
        return null;
    }
}
