const { cmd } = require("../command");
const axios = require("axios");
const yts = require("yt-search");
const config = require("../config");

// Reply Handler එක ගබඩා කිරීමට තාවකාලික Object එකක්
const songReplyStore = {};

cmd({
    pattern: "song",
    alias: ["yta", "mp3", "play"],
    react: "🎧",
    desc: "Download YouTube MP3 with selection menu",
    category: "download",
    filename: __filename,
}, async (bot, mek, m, { from, q, reply, userSettings, prefix }) => {
    try {
        if (!q) return reply("🎧 *ZANTA-MD SONG SEARCH*\n\nExample: .song alone");

        const search = await yts(q);
        const video = search.videos[0];
        if (!video) return reply("❌ No results found on YouTube.");

        const settings = userSettings || global.CURRENT_BOT_SETTINGS || {};
        const botName = settings.botName || config.DEFAULT_BOT_NAME || "ZANTA-MD";
        const isButtonsOn = settings.buttons === 'true';

        let msg = `🎵 *ZANTA AUDIO PLAYER* 🎵\n\n` +
                  `📝 *Title:* ${video.title}\n` +
                  `👤 *Artist:* ${video.author.name}\n` +
                  `⏱️ *Duration:* ${video.timestamp}\n` +
                  `🔗 *Link:* ${video.url}\n\n` +
                  (isButtonsOn ? `ꜱᴇʟᴇᴄᴛ 👇` : `*Reply with a number:* \n\n1️⃣ *Audio File* (MPEG)\n2️⃣ *Document File* (MP3)\n\n> *© ZANTA-MD SONG SERVICE*`);

        const contextInfo = {
            forwardingScore: 999,
            isForwarded: true,
            forwardedNewsletterMessageInfo: {
                newsletterJid: "120363406265537739@newsletter",
                newsletterName: "𝒁𝑨𝑵𝑻𝑨-𝑴𝑫 𝑶𝑭𝑭𝑰𝑪𝑰𝑨𝑳 </>",
                serverMessageId: 100
            }
        };

        if (isButtonsOn) {
            // --- BUTTONS LOGIC ---
            return await bot.sendMessage(from, {
                image: { url: video.thumbnail },
                caption: msg,
                footer: `© ${botName}`,
                buttons: [
                    { buttonId: `${prefix}ytsong_audio ${video.url}`, buttonText: { displayText: "🎵 AUDIO" }, type: 1 },
                    { buttonId: `${prefix}ytsong_doc ${video.url}`, buttonText: { displayText: "📂 DOCUMENT" }, type: 1 }
                ],
                headerType: 4,
                contextInfo
            }, { quoted: mek });
        } else {
            // --- REPLY SELECTION LOGIC ---
            const sentMsg = await bot.sendMessage(from, { 
                image: { url: video.thumbnail }, 
                caption: msg,
                contextInfo
            }, { quoted: mek });

            // මේ මැසේජ් එකේ ID එකට අදාළව වීඩියෝ ලින්ක් එක මතක තබා ගැනීම
            const messageId = sentMsg.key.id;
            songReplyStore[messageId] = video.url;

            // විනාඩි 5 කින් මතකයෙන් ඉවත් කරන්න
            setTimeout(() => { delete songReplyStore[messageId]; }, 5 * 60 * 1000);
        }
        
    } catch (e) {
        reply("❌ *Error:* " + e.message);
    }
});

// --- මැසේජ් එකකට රිප්ලයි කළ විට ක්‍රියාත්මක වන කොටස ---
// මෙය index.js හි වෙනස්කම් අවශ්‍ය නොවන පරිදි සකසා ඇත
cmd({
    on: "text"
}, async (bot, mek, m, { from, body, reply, prefix }) => {
    if (!m.quoted || !songReplyStore[m.quoted.id]) return;

    const videoUrl = songReplyStore[m.quoted.id];
    const choice = body.trim();

    if (choice === "1") {
        delete songReplyStore[m.quoted.id]; // එක පාරක් පාවිච්චි කළ පසු මකා දමන්න
        await downloadAndSend(bot, mek, from, videoUrl, "audio", reply);
    } else if (choice === "2") {
        delete songReplyStore[m.quoted.id];
        await downloadAndSend(bot, mek, from, videoUrl, "document", reply);
    }
});

// පොදු ඩවුන්ලෝඩ් ෆන්ක්ෂන් එක
async function downloadAndSend(bot, mek, from, url, type, reply) {
    try {
        await mek.react("📥");
        const downloadUrl = await getDownloadLink(url);
        if (!downloadUrl) return reply("❌ Download link not found.");

        if (type === "audio") {
            await bot.sendMessage(from, { 
                audio: { url: downloadUrl }, 
                mimetype: "audio/mpeg", 
                ptt: false 
            }, { quoted: mek });
        } else {
            await bot.sendMessage(from, { 
                document: { url: downloadUrl }, 
                mimetype: "audio/mpeg", 
                fileName: `ZANTA-MD_SONG.mp3`,
                caption: "> *© Generated by ZANTA-MD*"
            }, { quoted: mek });
        }
        await mek.react("✅");
    } catch (e) {
        reply("❌ Error: " + e.message);
    }
}

async function getDownloadLink(videoUrl) {
    try {
        const apiUrl = `https://api-site-x-by-manul.vercel.app/convert?mp3=${encodeURIComponent(videoUrl)}&apikey=Manul-Official`;
        const response = await axios.get(apiUrl);
        if (response.data?.status && response.data.data?.url) return response.data.data.url;

        const backupUrl = `https://api.giftedtech.my.id/api/download/dlmp3?url=${encodeURIComponent(videoUrl)}&apikey=gifted`;
        const backup = await axios.get(backupUrl);
        return backup.data.result?.download_url;
    } catch (e) { return null; }
}
