const { cmd } = require("../command");
const axios = require("axios");
const yts = require("yt-search");
const config = require("../config");

cmd({
    pattern: "song",
    alias: ["yta", "mp3", "play"],
    react: "🎧",
    desc: "Download YouTube MP3 with selection menu",
    category: "download",
    filename: __filename,
}, async (bot, mek, m, { from, q, reply, userSettings, prefix }) => {
    try {
        if (!q) return reply("🎧 *ZANTA-MD SONG SEARCH*\n\nExample: .song alone");

        const search = await yts(q);
        const video = search.videos[0];
        if (!video) return reply("❌ No results found on YouTube.");

        const settings = userSettings || global.CURRENT_BOT_SETTINGS || {};
        const botName = settings.botName || config.DEFAULT_BOT_NAME || "ZANTA-MD";
        const isButtonsOn = settings.buttons === 'true';

        let msg = `🎵 *ZANTA AUDIO PLAYER* 🎵\n\n` +
                  `📝 *Title:* ${video.title}\n` +
                  `👤 *Artist:* ${video.author.name}\n` +
                  `⏱️ *Duration:* ${video.timestamp}\n` +
                  `🔗 *Link:* ${video.url}\n\n` +
                  (isButtonsOn ? `ꜱᴇʟᴇᴄᴛ 👇` : `*Reply with a number:* \n\n1️⃣ *Audio File* (MPEG)\n2️⃣ *Document File* (MP3)\n\n> *© ZANTA-MD SONG SERVICE*`);

        const contextInfo = {
            forwardingScore: 999,
            isForwarded: true,
            forwardedNewsletterMessageInfo: {
                newsletterJid: "120363406265537739@newsletter",
                newsletterName: "𝒁𝑨𝑵𝑻𝑨-𝑴𝑫 𝑶𝑭𝑭𝑰𝑪𝑰𝑨𝑳 </>",
                serverMessageId: 100
            }
        };

        if (isButtonsOn) {
            // --- BUTTONS පෙන්වීම ---
            return await bot.sendMessage(from, {
                image: { url: video.thumbnail },
                caption: msg,
                footer: `© ${botName} • Song Downloader`,
                buttons: [
                    { buttonId: `${prefix}ytsong_audio ${video.url}`, buttonText: { displayText: "🎵 AUDIO" }, type: 1 },
                    { buttonId: `${prefix}ytsong_doc ${video.url}`, buttonText: { displayText: "📂 DOCUMENT" }, type: 1 }
                ],
                headerType: 4,
                contextInfo
            }, { quoted: mek });
        } else {
            // --- REPLY MENU (Selection) පෙන්වීම ---
            const sentMsg = await bot.sendMessage(from, { 
                image: { url: video.thumbnail }, 
                caption: msg,
                contextInfo
            }, { quoted: mek });

            // index.js එකේ logic එකට හසු වීමට ID එක Save කිරීම
            // මෙතන Map එකේ නම index.js එකේ නමට සමාන විය යුතුයි
            if (global.lastSongMessage) {
                global.lastSongMessage.set(from, sentMsg.key.id);
                setTimeout(() => global.lastSongMessage.delete(from), 3 * 60 * 1000);
            }
        }
        
    } catch (e) {
        console.log("SONG ERROR:", e);
        reply("❌ *Error:* " + e.message);
    }
});

// --- 1. AUDIO FILE HANDLER ---
cmd({
    pattern: "ytsong_audio",
    dontAddCommandList: true,
    filename: __filename,
}, async (bot, mek, m, { from, q, reply }) => {
    try {
        if (!q) return;
        await m.react("📥");
        const finalLink = await getDownloadLink(q);
        if (!finalLink) return reply("❌ Download link not found.");

        await bot.sendMessage(from, { 
            audio: { url: finalLink }, 
            mimetype: "audio/mpeg", 
            ptt: false 
        }, { quoted: mek });
        await m.react("✅");
    } catch (e) { reply("❌ Audio Error"); }
});

// --- 2. DOCUMENT FILE HANDLER ---
cmd({
    pattern: "ytsong_doc",
    dontAddCommandList: true,
    filename: __filename,
}, async (bot, mek, m, { from, q, reply }) => {
    try {
        if (!q) return;
        await m.react("📥");
        const finalLink = await getDownloadLink(q);
        if (!finalLink) return reply("❌ Download link not found.");

        await bot.sendMessage(from, { 
            document: { url: finalLink }, 
            mimetype: "audio/mpeg", 
            fileName: `ZANTA-MD_SONG.mp3`,
            caption: "> *© Generated by ZANTA-MD*"
        }, { quoted: mek });
        await m.react("✅");
    } catch (e) { reply("❌ Document Error"); }
});

async function getDownloadLink(videoUrl) {
    try {
        const apiUrl = `https://api-site-x-by-manul.vercel.app/convert?mp3=${encodeURIComponent(videoUrl)}&apikey=Manul-Official`;
        const response = await axios.get(apiUrl);
        if (response.data?.status && response.data.data?.url) return response.data.data.url;

        const backupUrl = `https://api.giftedtech.my.id/api/download/dlmp3?url=${encodeURIComponent(videoUrl)}&apikey=gifted`;
        const backup = await axios.get(backupUrl);
        return backup.data.result?.download_url;
    } catch (e) { return null; }
}
