const { cmd } = require("../command");
const axios = require("axios");
const yts = require("yt-search");
const config = require("../config");

cmd({
    pattern: "song",
    alias: ["yta", "mp3", "play"],
    react: "🎧",
    desc: "Download YouTube MP3 with selection menu",
    category: "download",
    filename: __filename,
}, async (bot, mek, m, { from, q, reply, userSettings, prefix }) => {
    try {
        if (!q) return reply("🎧 *ZANTA-MD SONG SEARCH*\n\nExample: .song alone");

        const search = await yts(q);
        const video = search.videos[0];
        if (!video) return reply("❌ No results found on YouTube.");

        const settings = userSettings || global.CURRENT_BOT_SETTINGS || {};
        const botName = settings.botName || config.DEFAULT_BOT_NAME || "ZANTA-MD";

        // Reply Menu එක සකස් කිරීම
        let msg = `🎵 *ZANTA AUDIO PLAYER* 🎵\n\n` +
                  `📝 *Title:* ${video.title}\n` +
                  `👤 *Artist:* ${video.author.name}\n` +
                  `⏱️ *Duration:* ${video.timestamp}\n` +
                  `🔗 *Link:* ${video.url}\n\n` +
                  `*Reply with a number:* \n\n` +
                  `1️⃣ *Audio File* (MPEG)\n` +
                  `2️⃣ *Document File* (MP3)\n\n` +
                  `> *© ZANTA-MD SONG SERVICE*`;

        // thumbnail එක සමඟ පණිවිඩය යැවීම
        const sentMsg = await bot.sendMessage(from, { 
            image: { url: video.thumbnail }, 
            caption: msg 
        }, { quoted: mek });

        // මෙතනදී index.js එකට හඳුනාගැනීම සඳහා caption එකට විශේෂ ලකුණක් (🎵 *SONG DOWNLOADER*) එකතු කිරීම හෝ 
        // වෙනත් ක්‍රමයක් භාවිතා කළ හැක. 
        // නමුත් වඩාත් නිවැරදි ක්‍රමය වන්නේ වෙනමම commands දෙකක් සාදා ගැනීමයි.
        
    } catch (e) {
        console.log("SONG ERROR:", e);
        reply("❌ *Error:* " + e.message);
    }
});

// --- 1. AUDIO FILE HANDLER ---
cmd({
    pattern: "ytsong_audio",
    dontAddCommandList: true,
    filename: __filename,
}, async (bot, mek, m, { from, q, reply }) => {
    try {
        if (!q) return;
        const finalLink = await getDownloadLink(q);
        if (!finalLink) return reply("❌ Download link not found.");

        await bot.sendMessage(from, { 
            audio: { url: finalLink }, 
            mimetype: "audio/mpeg", 
            ptt: false 
        }, { quoted: mek });
        await m.react("✅");
    } catch (e) { reply("❌ Audio Error"); }
});

// --- 2. DOCUMENT FILE HANDLER ---
cmd({
    pattern: "ytsong_doc",
    dontAddCommandList: true,
    filename: __filename,
}, async (bot, mek, m, { from, q, reply }) => {
    try {
        if (!q) return;
        const finalLink = await getDownloadLink(q);
        if (!finalLink) return reply("❌ Download link not found.");

        await bot.sendMessage(from, { 
            document: { url: finalLink }, 
            mimetype: "audio/mpeg", 
            fileName: `ZANTA-MD_SONG.mp3`,
            caption: "> *© Generated by ZANTA-MD*"
        }, { quoted: mek });
        await m.react("✅");
    } catch (e) { reply("❌ Document Error"); }
});

// --- API Logic එක පොදු Function එකක් ලෙස ---
async function getDownloadLink(videoUrl) {
    try {
        // Manul API
        const apiUrl = `https://api-site-x-by-manul.vercel.app/convert?mp3=${encodeURIComponent(videoUrl)}&apikey=Manul-Official`;
        const response = await axios.get(apiUrl);
        if (response.data?.status && response.data.data?.url) return response.data.data.url;

        // Backup API
        const backupUrl = `https://api.giftedtech.my.id/api/download/dlmp3?url=${encodeURIComponent(videoUrl)}&apikey=gifted`;
        const backup = await axios.get(backupUrl);
        return backup.data.result?.download_url;
    } catch (e) {
        return null;
    }
}
